export default {
  HOME_ACTION_SELECT: 'TODO_ACTION_RECORD',
  HOME_ACTION_SELECT_SUB_MENU: 'HOME_ACTION_SELECT_SUB_MENU',
  HOME_ACTION_MODAL_VISIBLE: 'HOME_ACTION_MODAL_VISIBLE',
  HOME_ACTION_MODAL_SAVE: 'HOME_ACTION_MODAL_SAVE',
  HOME_ACTION_DO_SEARCH: 'HOME_ACTION_DO_SEARCH'
}
