# 系统的 appCode 唯一标示
appCode: HUM

# 系统的标题
pageTitle: 禾优曼管理系统

dbOption:
    host : 'localhost'
    port : '3306'
    user : 'root'
    password : 'Anthony1021'
    database : 'hum'
    connectionLimit: 20
apiPrefix: '/api'
server:
  port: 8080
  devPort : 9005
  debugPort: 7005
